
image:
  file: .gitpod.Dockerfile
tasks:
  - init: cd demo && ./gradlew eclipse
       && psql -f /workspace/spring-thy-pg/DB/create.sql
    command: export TZ="Asia/Tokyo"

vscode:
  extensions:
    - pivotal.vscode-boot-dev-pack
    - pivotal.vscode-spring-boot
    - vscjava.vscode-spring-boot-dashboard
    - vscjava.vscode-spring-initializr
    - gabrielbb.vscode-lombok
    - redhat.java
    - vscjava.vscode-java-test
    - vscjava.vscode-java-debug
    - pivotal.vscode-concourse
    - pivotal.vscode-manifest-yaml
    - vscodevim.vim
    - leodevbro.blockman
    - coenraads.bracket-pair-colorizer-2
